"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./activeUser"));
__export(require("./apiVersionNotAvailable"));
__export(require("./apiVersionNotImplemented"));
__export(require("./appProblem"));
__export(require("./badRequest"));
__export(require("./base"));
__export(require("./bl"));
__export(require("./corsDisabled"));
__export(require("./duplicateEndUsers"));
__export(require("./featureUnavailable"));
__export(require("./incompleteRequestBody"));
__export(require("./indirectCollectionAccessDisallowed"));
__export(require("./insufficientCredentials"));
__export(require("./invalidCredentials"));
__export(require("./invalidIdentifier"));
__export(require("./invalidQuerySyntax"));
__export(require("./jsonParse"));
__export(require("./kinvey"));
__export(require("./kinveyInternalErrorRetry"));
__export(require("./kinveyInternalErrorStop"));
__export(require("./missingConfiguration"));
__export(require("./missingQuery"));
__export(require("./missingRequestHeader"));
__export(require("./missingRequestParameter"));
__export(require("./mobileIdentityConnect"));
__export(require("./networkConnection"));
__export(require("./noActiveUser"));
__export(require("./noResponse"));
__export(require("./notFound"));
__export(require("./parameterValueOutOfRange"));
__export(require("./popup"));
__export(require("./query"));
__export(require("./resultSetSizeExceeded"));
__export(require("./server"));
__export(require("./staleRequest"));
__export(require("./sync"));
__export(require("./timeout"));
__export(require("./userAlreadyExists"));
__export(require("./writesToCollectionDisallowed"));
//# sourceMappingURL=index.js.map