import { exists } from './exists';
import { forgotUsername } from './forgotUsername';
import { login } from './login';
import { loginWithRedirectUri } from './loginWithRedirectUri';
import { loginWithUsernamePassword } from './loginWithUsernamePassword';
import { loginWithMIC, AuthorizationGrant } from './loginWithMIC';
import { logout } from './logout';
import { lookup } from './lookup';
import { me } from './me';
import { remove } from './remove';
import { resetPassword } from './resetPassword';
import { restore } from './restore';
import { signup } from './signup';
import { signUpWithIdentity } from './signupWithIdentity';
import { update } from './update';
import { getActiveUser } from './getActiveUser';
import { User } from './user';
import { verifyEmail } from './verifyEmail';
// import { registerForLiveService } from './registerForLiveService';
// import { unregisterForLiveService } from './unregisterForLiveService';

(User as any).AuthorizationGrant = AuthorizationGrant;
(User as any).exists = exists;
(User as any).forgotUsername = forgotUsername;
(User as any).login = login;
(User as any).loginWithRedirectUri = loginWithRedirectUri;
(User as any).loginWithUsernamePassword = loginWithUsernamePassword;
(User as any).loginWithMIC = loginWithMIC;
(User as any).logout = logout;
(User as any).lookup = lookup;
(User as any).me = me;
(User as any).remove = remove;
(User as any).resetPassword = resetPassword;
(User as any).restore = restore;
(User as any).signup = signup;
(User as any).signUpWithIdentity = signUpWithIdentity;
(User as any).update = update;
(User as any).verifyEmail = verifyEmail;
(User as any).getActiveUser = getActiveUser;
// (User as any).registerForLiveService = registerForLiveService;
// (User as any).unregisterForLiveService = unregisterForLiveService;

export { User };
